config/routes.rb
Rails.application.routes.draw do
  # GOD MODE
  resources :admins
  
  # User Authentication with devise. Customized default paths
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'enroll' }
  
  # Courses, Cohorts, Instructors, Students
  resources :courses, except: [:show] do
    resources :cohorts, only: [:new, :create, :destroy] do
      resources :students, only:[:new, :create, :destroy] 
      resources :instructors, only: [:new, :create, :destroy]
    end
  end
  get 'courses/:id' => 'courses#show', as: 'course_show'
  
  # Cohorts only 
  resources :cohorts, only: [:show, :edit, :update, :index], except: [:show]
  get 'cohorts/:id' => 'cohorts#show', as: 'cohort_show'

  # Instructors only
  resources :instructors, only: [:show, :edit, :update, :index]

  # Students only
  resources :students, only: [:show, :edit, :update, :index]

  # Other MAIN pages
  get 'about-us' => 'pages#about'
  get 'contact-us' => 'pages#contact'
  get 'dashboard' => 'pages#dashboard'

  # HOME
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cohort.rb
class Cohort < ApplicationRecord
  # For friendly URLs
  extend FriendlyId
  friendly_id :name, use: :slugged
  
  # Data Validation
  validates_presence_of :name, :start_date, :end_date
  validates :name, length: { minimum: 8, maximum: 80 }


  # Associations
  belongs_to :course
  has_one :instructor, dependent: :destroy
  has_many :students, dependent: :destroy

end

app/controllers/cohorts_controller.rb
class CohortsController < ApplicationController
  before_action :set_cohort, only: [:edit, :update, :show, :destroy]
  before_action :set_parent, only: [:new, :create, :destroy]
  # before_action authenticate_user!
  access all: [:show, :index], user: {except: [:destroy, :new, :create, :update, :edit]}, instructor: {except: [:destroy, :new, :create, :update, :edit]}, headmaster: :all

  def index
    @cohorts = Cohort.all
  end

  def show

  end

  def new 
    @cohort = Cohort.new
  end

  def create
    @cohort = Cohort.new(cohort_params)
    @cohort.course_id = @course.id

    if @cohort.save
      p "Cohort Added"
      notice = 'Cohort Added!'
      redirect_to @cohort
    else
        p "Denied"
        render 'new'
    end
  end

  def edit

  end

  def update
    respond_to do |format|
      if @cohort.update(cohort_params) 
        p 'Updated'
        format.html { redirect_to @cohort, notice: 'Cohort successfully updated.' }
      else
        p 'Denied'
        format.html { render :edit }
      end
    end
  end

  def destroy
    p 'Removed Cohort'
    @cohort.destroy
    respond_to do |format|
      format.js
      format.html { redirect_to course_show_path(@course.slug) }
    end
  end

  private 

  def cohort_params
    params.require(:cohort).permit(:name, :start_date, :end_date)
  end

  def set_cohort
    @cohort = Cohort.friendly.find(params[:id])
  end

  def set_parent
    @course = Course.friendly.find(params[:course_id])
  end
end

app/helpers/cohorts_helper.rb
module CohortsHelper
end

app/views/cohorts/_form.html.erb
<div class="universal-form">

  <%= form_for([@course, @cohort]) do |f| %>

    <div>
      <%= f.text_field :name, placeholder: 'Cohort Name', autofocus: true %>
    </div>

    <div>
      <%= f.date_field :start_date, placeholder: 'Start Date' %>
    </div>

    <div>
      <%= f.date_field :end_date, placeholder: 'End Date' %>
    </div>

    <div class="submit-btn">
      <%= f.submit %>
    </div>

  <% end %>

</div>

app/views/cohorts/destroy.js.erb
$('.denied').bind('ajax:success', function() {
  console.log('deleting...');
  $(this).closest('div').fadeOut();
});

app/views/cohorts/edit.html.erb
<div class="cohorts-form">

  <div class="back-link">
    <%= link_to 'Back', cohort_path %>
  </div>

  <h1> Update Cohort Information </h1>

  <%= render 'form', cohort: @cohort %>

</div>

app/views/cohorts/index.html.erb
<div class="cohorts-index">

  <%= render 'shared/sidebar' %>

  <div class="cohorts-grid">
    <h1> List of Active Cohorts </h1>

    <div class="cohorts-list">
      <% @cohorts.each do |cohort| %>
        <div class="cohorts-info">
          <h3> <%= link_to cohort.name, cohort_show_path(cohort.slug) %> </h3>
          <p>  From: <%= cohort.start_date %> </p>
          <p>  To: <%= cohort.end_date %> </p>
          <p>  Instructor: <span class="link-instructor"><%= link_to cohort.instructor.full_name, instructor_path(cohort.instructor.slug) unless cohort.instructor == nil  %></span> </p>
          <p>  Attendees: <%= cohort.students.count %> </p>
          <section class="cohorts-links">
            <%= link_to 'Edit Details', edit_cohort_path(cohort.slug) %>
            <%= link_to 'Terminate Cohort', course_cohort_path(cohort.course_id, cohort.slug), method: :delete, data: { confirm: 'Are you sure?', remote: true }, class: 'denied' %>
          </section>
        </div>
      <% end %>
    </div>
  </div>

</div>

app/views/cohorts/new.html.erb
<div class="cohorts-form">

  <div class="back-link">
    <%= link_to 'Back', course_path(@course.id)  %>
  </div>

  <h1> Enter Cohort Information </h1>

  <%= render 'form', cohort: @cohort %>

</div>

app/views/cohorts/show.html.erb
<div class="cohorts-show">

  <div class="back-links">
    <%= link_to 'Back', course_show_path(@cohort.course_id) %>
  </div>


  <div class="cohort-details">
    <h1> <%= @cohort.name %> | cohort details</h1>
    
    <div class="dates">
      <p> Begin: <%= @cohort.start_date %> </p>
      <p> End: <%= @cohort.end_date %> </p>
    </div>
  </div>
  <div class="cohorts-links">
      <%= link_to 'Add Students', new_course_cohort_student_path(@cohort.course_id, @cohort.id) %>
      <%= link_to 'Assign Instructor', new_course_cohort_instructor_path(@cohort.course_id, @cohort.id) %>
      <%= link_to 'Edit Details', edit_cohort_path %>
  </div>
  <div class="cohort-info">
    <h3> Instructor </h3>

    <div>
      <% i = @cohort.instructor %> 
      <% if i %>
      <span class="emphasis">
        <%= link_to "#{i.full_name}", i %>
      </span>
      <span class="terminate">
        <%= link_to "Terminate", course_cohort_instructor_path(i.course_id, i.cohort_id, i.slug), method: :delete, data: { confirm: 'Are you sure?', remote: true }, class: 'denied' %>
      </span>
      <% end %>
    </div>

    <h3> Attendees </h3>

      <% @cohort.students.each do |s| %>
    <div class="cohort-students">
        <span class="emphasis">
          <%= link_to "#{s.full_name}", s %>
        </span>
        <span class="terminate">
          <%= link_to "Expel", course_cohort_student_path(s.course_id, s.cohort_id, s.slug), method: :delete, data: { confirm: 'Are you sure?', remote: true }, class: 'denied' %>
        </span>
    </div>
      <% end %>
  </div>

</div>