config/routes.rb
Rails.application.routes.draw do
  # GOD MODE
  resources :admins
  
  # User Authentication with devise. Customized default paths
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'enroll' }
  
  # Courses, Cohorts, Instructors, Students
  resources :courses, except: [:show] do
    resources :cohorts, only: [:new, :create, :destroy] do
      resources :students, only:[:new, :create, :destroy] 
      resources :instructors, only: [:new, :create, :destroy]
    end
  end
  get 'courses/:id' => 'courses#show', as: 'course_show'
  
  # Cohorts only 
  resources :cohorts, only: [:show, :edit, :update, :index], except: [:show]
  get 'cohorts/:id' => 'cohorts#show', as: 'cohort_show'

  # Instructors only
  resources :instructors, only: [:show, :edit, :update, :index]

  # Students only
  resources :students, only: [:show, :edit, :update, :index]

  # Other MAIN pages
  get 'about-us' => 'pages#about'
  get 'contact-us' => 'pages#contact'
  get 'dashboard' => 'pages#dashboard'

  # HOME
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/instructor.rb
class Instructor < ApplicationRecord
  # Friendly URLs
  extend FriendlyId
  friendly_id :first_name, use: :slugged

  # Data Validation
  validates_presence_of :first_name, :last_name, :age, :education, :salary
  validates :age, numericality: { greater_than: 18, less_than: 150, only_integer: true }
  validates :salary, numericality: { greater_than: 0 }

  # Associations
  belongs_to :cohort
  belongs_to :course
  # For devise user association
  has_one :user, as: :meta


  def full_name 
    self.first_name + ' ' + self.last_name
  end
end

app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController
  before_action :set_instructor, only: [:edit, :update, :show, :destroy]
  before_action :set_parent, only: [:new, :create, :destroy]
  access all: [:index], user: {except: [:destroy, :new, :create, :update, :edit, :show]}, instructor: {except: [:destroy, :new, :create, :update, :edit, :show]}, headmaster: :all
  
  def index 
    @instructors = Instructor.all
  end

  def show

  end

  def new
    @instructor = Instructor.new
  end

  def create 
    @instructor = Instructor.new(instructor_params)
    @instructor.course_id = @course.id
    @instructor.cohort_id = @cohort.id 

    if @instructor.save
      p 'EUREKA'
      redirect_to cohort_show_path(@cohort.slug)
    else
      p 'Denied'
      render 'new'
    end
  end

  def destroy
    p 'Instructor has been denied!'
    @instructor.destroy
    respond_to do |format|
      format.js
      format.html { redirect_to cohort_show_path(@cohort.slug) }
    end
  end

  def edit

  end

  def update
    respond_to do |format|
      if @instructor.update(instructor_params) 
        p 'Updated'
        format.html { redirect_to @instructor, notice: 'Instructor bio successfully updated.' }
      else
        p 'Denied'
        format.html { render :edit }
      end
    end
  end


  private

  def instructor_params
    params.require(:instructor).permit(:first_name, :last_name, :age, :education, :salary)
  end

  def set_instructor 
    @instructor = Instructor.friendly.find(params[:id])
  end

  def set_parent
    @course = Course.friendly.find(params[:course_id])
    @cohort = Cohort.friendly.find(params[:cohort_id])
  end
end

app/helpers/instructors_helper.rb
module InstructorsHelper
end

app/views/instructors/_form.html.erb
<div class="universal-form">

  <%= form_for([@course, @cohort, @instructor]) do |f| %>

    <div>
      <%= f.text_field :first_name, placeholder: 'First Name', autofocus: true %>
    </div>

    <div>
      <%= f.text_field :last_name, placeholder: 'Last Name' %>
    </div>

    <div>
      <%= f.text_field :age, placeholder: 'Age' %>
    </div>

    <div>
      <%= f.radio_button :education, 'HS', :checked => true %> 
      <%= label :education_hs, 'HS' %>
      <%= f.radio_button :education, 'College' %>
      <%= label :education_college, 'College' %>
      <%= f.radio_button :education, 'Masters' %>
      <%= label :education_masters, 'Masters' %>
      <%= f.radio_button :education, 'PHD' %>
      <%= label :education_phd, 'PHD' %>
    </div>

    <div>
      <%= f.text_field :salary, placeholder: 'Salary' %>
    </div>

    <div class="submit-btn">
      <%= f.submit %>
    </div>

  <% end %>

</div>

app/views/instructors/destroy.js.erb
$('.denied').bind('ajax:success', function() {
  console.log('deleting...');
  $(this).closest('div').fadeOut();
});

app/views/instructors/edit.html.erb
<div class="instructors-form">

  <div class="back-link">
    <%= link_to 'Back', instructor_path %>
  </div>

  <h1> Update Instructor Information </h1>

  <%= render 'form', instructor: @instructor %>

</div>

app/views/instructors/index.html.erb
<div class="instructors-index">

  <%= render 'shared/sidebar' %>

  <div class="instructors-grid">
  
    <h1> Our Notable Instructors </h1>
    <div class="instructors-list">
      <% @instructors.each do |instructor| %>
      <div class="instructors-info">
        <h3> <%= link_to instructor.full_name, instructor_path(instructor.slug) %> </h3>
        <p> Course id#: <%= instructor.course_id %> </p>
        <p> Cohort id#: <%= instructor.cohort_id %> </p>
          <section class="instructors-links">
            <%= link_to 'Edit Details', edit_instructor_path(instructor.slug) %>
            <span class="terminate">
              <%= link_to 'Terminate Instructor', course_cohort_instructor_path(instructor.course_id, instructor.cohort_id, instructor.id), method: :delete, data: { confirm: 'Are you sure?', remote: true }, class: 'denied' %> 
            </span>
          </section>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/instructors/new.html.erb
<div class="instructors-form">

  <div class="back-link">
    <%= link_to 'Back', cohort_path(@cohort.id) %>
  </div>

  <h1> Enter Instructor Information </h1>

  <%= render 'form', instructor: @instructor %>

</div>

app/views/instructors/show.html.erb
<div class="profile-grid">

  <h1> Instructor Dossier </h1>

  <div class="bio-links">
    <%= link_to 'Back to Cohort', cohort_show_path(@instructor.cohort_id) %> 
    <%= link_to 'Edit Bio', edit_instructor_path %>
  </div>

  <div class="bio-details">
    <h2><%= "#{@instructor.last_name}, #{@instructor.first_name}" %> </h2>
    <p> Age: <%= @instructor.age %> </p>
    <p> Education: <%= @instructor.education %> </p>
    <p> Annual Salary: $ <%= @instructor.salary %> </p>
  </div>

</div>