config/routes.rb
Rails.application.routes.draw do
  # GOD MODE
  resources :admins
  
  # User Authentication with devise. Customized default paths
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'enroll' }
  
  # Courses, Cohorts, Instructors, Students
  resources :courses, except: [:show] do
    resources :cohorts, only: [:new, :create, :destroy] do
      resources :students, only:[:new, :create, :destroy] 
      resources :instructors, only: [:new, :create, :destroy]
    end
  end
  get 'courses/:id' => 'courses#show', as: 'course_show'
  
  # Cohorts only 
  resources :cohorts, only: [:show, :edit, :update, :index], except: [:show]
  get 'cohorts/:id' => 'cohorts#show', as: 'cohort_show'

  # Instructors only
  resources :instructors, only: [:show, :edit, :update, :index]

  # Students only
  resources :students, only: [:show, :edit, :update, :index]

  # Other MAIN pages
  get 'about-us' => 'pages#about'
  get 'contact-us' => 'pages#contact'
  get 'dashboard' => 'pages#dashboard'

  # HOME
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_footer.html.erb
<footer>
  <% if current_user == nil %>
  <nav>
    <ul>
      <li><a href="#"><i class="flaticon-facebook"></i></a></li>
      <li><a href="#"><i class="flaticon-instagram"></i></a></li>
      <li><a href="#"><i class="flaticon-youtube"></i></a></li>
      <li><a href="#"><i class="flaticon-linkedin"></i></a></li>
    </ul>
  </nav>
  <% end %>
  <span> <%= copyright_generator %> </span>

</footer>

app/views/shared/_header.html.erb
<header>

  <div id="logo">
    <%= image_tag "logo-2.png"%>

    <h1> Rubicks Academy </h1>
  </div>

  <%= render "shared/nav" %>

</header>

app/views/shared/_nav.html.erb
<nav class="main-nav">
  <ul>
    <% if current_user == nil %>
    <li><%= link_to "Home", root_path %></li>
    <li><%= link_to "About", about_us_path %></li>
    <li><%= link_to "Contact", '#' %></li>
    <li><%= login_helper %></li>
    <% else %>
    <li><%= login_helper %></li>
    <% end %>
  </ul>
</nav>

app/views/shared/_sidebar.html.erb
<aside class="sidebar">

    <h2> <%= check_user %></h2>

    <ul>
      <li><%= link_to 'Courses', courses_path %></li>
      <li><%= link_to 'Cohorts', cohorts_path %></li>
      <li><%= link_to 'Instructors', instructors_path %></li>
      <li><%= link_to 'Students', students_path %></li>
    </ul>
    
</aside>