config/routes.rb
Rails.application.routes.draw do
  # GOD MODE
  resources :admins
  
  # User Authentication with devise. Customized default paths
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'enroll' }
  
  # Courses, Cohorts, Instructors, Students
  resources :courses, except: [:show] do
    resources :cohorts, only: [:new, :create, :destroy] do
      resources :students, only:[:new, :create, :destroy] 
      resources :instructors, only: [:new, :create, :destroy]
    end
  end
  get 'courses/:id' => 'courses#show', as: 'course_show'
  
  # Cohorts only 
  resources :cohorts, only: [:show, :edit, :update, :index], except: [:show]
  get 'cohorts/:id' => 'cohorts#show', as: 'cohort_show'

  # Instructors only
  resources :instructors, only: [:show, :edit, :update, :index]

  # Students only
  resources :students, only: [:show, :edit, :update, :index]

  # Other MAIN pages
  get 'about-us' => 'pages#about'
  get 'contact-us' => 'pages#contact'
  get 'dashboard' => 'pages#dashboard'

  # HOME
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:edit, :update, :show, :destroy]
  # before_action authenticate_user!
  access all: [:show, :index], user: {except: [:destroy, :new, :create, :update, :edit]}, instructor: {except: [:destroy, :new, :create, :update, :edit]}, headmaster: :all

  def index
    @courses = Course.all
  end

  def show

  end

  def new
    @course = Course.new
  end

  def create 
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        p "Course Added"
        format.html { redirect_to courses_path, notice: 'Added a new course!' }
      else
        p "Denied"
        format.html { render :new }
      end
    end
  end

  def edit

  end

  def update
    respond_to do |format|
      if @course.update(course_params) 
        p 'Updated'
        format.html { redirect_to courses_path, notice: 'Course successfully updated.' }
      else
        p 'Denied'
        format.html { render :edit }
      end
    end
  end

  def destroy
    p 'Removed Course'
    @course.destroy
    respond_to do |format|
      format.js
      format.html { redirect_to courses_url, notice: 'Course removed!' }
    end
  end


  private 

  def course_params
    params.require(:course).permit(:title, :details, :total_hours)
  end
    
  def set_course 
    @course = Course.friendly.find(params[:id])
  end

end

app/helpers/courses_helper.rb
module CoursesHelper

end

app/views/courses/_form.html.erb
<div class="universal-form">

  <%= form_for(@course) do |f| %>

    <div>
      <%= f.text_field :title, placeholder: 'Course Title', autofocus: true %>
    </div>

    <div>
      <%= f.text_field :total_hours, placeholder: 'Total Hours' %>
    </div>

    <div>
      <%= f.text_area :details, placeholder: 'Course Details' %>
    </div>

    <div class="submit-btn">
      <%= f.submit %>
    </div>

  <% end %>

</div>

app/views/courses/destroy.js.erb
$('.denied').bind('ajax:success', function() {
  console.log('deleting...');
  $(this).closest('div').fadeOut();
});

app/views/courses/edit.html.erb
<div class="courses-form">

  <div class="back-link">

    <%= link_to 'Back', courses_path %>
    
  </div>

  <h1>Update Course Information</h1>

  <%= render 'form', course: @course %>

</div>

app/views/courses/index.html.erb
<div class="courses-index">

  <%= render 'shared/sidebar' %>

  <div class="courses-grid">
    <h1> Course List </h1>

    <div class="courses__create">
      <%= link_to "Create Course", new_course_path  %>
    </div>

    <div class="courses__card">
      <% @courses.each do |c| %>
      <div class="details">
        <h3><%= link_to c.title, course_show_path(c) %></h3>
        <p>Total Hours: <%= c.total_hours %></p>
        <h4>Course Details > > ></h4>
        <p><%= c.details %></p>
        <p> Instructors: <%= c.instructors.count %> </p>
        <p> Attendees: <%= c.students.count %> </p>
        <section class="courses-links">
            <%= link_to 'Edit', edit_course_path(c) %> 
            <%= link_to 'Remove', course_path(c), method: :delete, data: { confirm: 'Are you sure?', remote: true }, class: 'denied' %>
        </section>
      </div>

      <% end %>
    </div>
  </div> 

</div>

app/views/courses/new.html.erb
<div class="courses-form">

  <div class="back-link">
    <%= link_to 'Back', courses_path %>
  </div>

  <h1>Enter Course Information</h1>


  <%= render 'form', course: @course %>


</div>

app/views/courses/show.html.erb
<div class="courses-show">

  <div class="back-links">
    <%= link_to 'Back', courses_path %>
  </div>
  
  <div class="course-details">
    <h1> <%= @course.title %> course </h1>

    <p>Total Hours: <%= @course.total_hours %></p>
    <p><%= @course.details %></p>
  </div>

  <div class="courses__cohorts">
    <h2> List of Cohorts </h3>

    <div class="cohorts-create">
      <%= link_to 'Add Cohort', new_course_cohort_path(@course.id) %> 
    </div>

    <% @course.cohorts.each do |cohort| %>
    <div class="cohorts-items">
      <span class="cohort-title"> <%= link_to "#{cohort.name}", cohort_show_path(cohort.slug) if cohort != nil %> </span>  &nbsp &nbsp <span class="terminate"> 
        <%= link_to 'Terminate Cohort', course_cohort_path(@course.slug, cohort.slug), method: :delete, data: { confirm: 'Are you sure?', remote: true }, class: 'denied' %> 
      </span>
    </div>
    <% end %>
  </div>

</div>